TD_MODEL = "../model/td/td_model.pth"
TD_MODEL_CONFIG = "../model/td/detection_config.json"
TSR_MODEL = "../model/tsr/tsr_model.pth"
TSR_MODEL_CONFIG = "../model/tsr/structure_config.json"
LAYOUT_DETECTION_MODEL = "../model/layout_model.pth"
LAYOUT_DETECTION_MODEL_CONFIG = "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"